### PR TITLE
Coupled dynamics

### PR DESCRIPTION
**Pull request by YorchMcM**
The example on coupled translational-rotational dynamics, using Phobos for that.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi, this example is awesome!!! 

I've gone through it and have made some modifications, mostly to bring the style and level of detail of the accompanying text in line with the rest of the examples. You can find my proposed modifications on this branch:

https://github.com/tudat-team/tudatpy-examples/tree/feature/couple_propagation

with this diff showing the exact modifications I've made.

https://github.com/tudat-team/tudatpy-examples/commit/7771de9a03aa35ed026556454dc473b5d59b138b

There's a few small todos, a couple are related to API reference entries that I should write (in particular related to the damping), and related to some additional comments that are needed in the helper functions of the code, to explain what/how the calculations are done. I actually think that many of your helper functions will be useful well beyond this example! Once we merge this, let's open an issue to remind us to merge these helper functions into tudatpy :)

I also have a small question on the choice of gravity field:
* Why no C21/S21?
* Why only define the gravity field of Phobos up to degree 2?

**Comment by YorchMcM** [comment]
Hi Dominic :D

Happy to hear you liked it :) And that the code is helpful beyond the
example itself. I will look in more detail into the modifications this
evening. I'll answer your questions now, though.

In the example, Phobos only has a quadrupole field (i.e. only C20 and C22).
This is a decision I made before figuring out that what was screwing the
simulation where the degree 1 harmonics. I never thought of revisiting it
when I did figure it out, mainly because for the illustrative purpose of
the example it doesn't really matter too much (I think) whether Phobos has
a 2/2 field or a 4/4 field. But we can always change it, I don't mind. Let
me know if you want me to do it.

So yeah. I'll let you know when I've looked through the changes, even if
it's just to say that they're awesome.

Cheers ;)

Jorge

**Comment by YorchMcM** [comment]
Hi Dominic :D

Sorry for the delay. I went over the modifications, I corrected some typos and I also did some of the TODOs. All the changes are in [my repo](https://github.com/YorchMcM/tudatpy-examples) and the changes are in [this diff](https://github.com/YorchMcM/tudatpy-examples/commit/66db5840fbab53031c3fb71e01046f7bca1ed674).

There is a problem, though. Me and my git illiteracy just made a mess for a few hours today and yesterday. The result is, the diff I send contains both my changes and your changes. So, the difference between what I had when I created the pull request, and the newest version with both our changes. Sorry for that, I have to figure myself out with git.

So yeah. Let me know what you think.

**Comment by DominicDirkx** [comment]
Hi Jorge, nice! The file as it is looks good, so whatever it is that went wrong with git luckily doesn't show up anymore. Next time we meet I can walk you through the correct git procedure. 

The open todos are now mainly on me, for documenting the damping algorithm in the API docs. Other than that, there's a couple pieces in the utility function that could with some extra explanation of what's going on, but let's go through it next time we meet in person as well, I think we can modify it in a couple of minutes.

I'm really excited to have this cool example up soon!!

**Comment by YorchMcM** [comment]
Hi Dominic.

Nice, happy to hear so many good things together :partying_face: 

As for our next in person meeting, it will not be earlier than the end of August. I am not sure how urgent the documentation on the auxiliaries is. If it is for example publication, we can go over them in an online meeting just so that the example doesn't have to sit still for the whole summer. I usually use Discord for these meetings where we have to look at each other's code, but whatever you prefer will also work. Alternatively, if it is not that pressing of a matter, we can take a look at them when I am back in Delft. In any case, feel free to send me a list of what kind of comments you think are most necessary and I will start working on those.

**Comment by YorchMcM** [comment]
So, I have added extra comments and documentation. While documenting the bring_inside_bounds_scalar algorithm, I thought a bit harder than last time and tested whether the reflect and centre things were really necessary, and turns out they weren't. So the function has been simplified.

And I think, the last thing missing is the API documentation for the damping features to be published. **And remember to remove all the TODOs that you find** right before merging.

**Pull request merged**
