### PR TITLE
Github action to sync tudat-space submodule

### PR DESCRIPTION
**Pull request by larshinueber**
This PR adds a Github action to update the submodule commit in tudat-space on each push to the tudatpy-examples master branch. It makes `tudatpy-examples` the leading repository for example applications (see #13 for a discussion on the workflow).

Changes include:
- Remove deprecated workflow files
- Add new workflow to sync tudat-space

# Before merging
- Review and merge https://github.com/tudat-team/tudat-space/pull/148 first
- Add a repository secret `GH_PAT` to tudatpy-examples with permissions to push to tudat-space

Any feedback is appreciated!

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Great to have this! Have you been able to test this already somehow?

**Comment by larshinueber** [comment]
Hi Dominic,

Yes, I have tested this in the dummy-repos https://github.com/larshinueber/foo-space/tree/submodules and https://github.com/larshinueber/foopy-examples/tree/submodules on the `submodules` branches.

If a change is made in `foopy-examples`, e.g. commit https://github.com/larshinueber/foopy-examples/commit/7b64f2a5493183d5ed1daebefa6af7b7091d8d23, the action will make a commit in `foo-space` like this: https://github.com/larshinueber/foo-space/commit/86e170f526326c169511c6fa9ce21e40814bc333. The commit message and authors can of course be changed if desired.
Here is the log file of the action: https://github.com/larshinueber/foopy-examples/actions/runs/10470939960/job/28997145747

The workflow files are fundamentally the same between the `tudat` repos and the `foo` repos, with the only changes being the branch names on which the workflow should be triggered and where the commit is pushed to.

Let me know if there is anything unclear :)

**Comment by DominicDirkx** [comment]
Great, thanks!

**Comment by DominicDirkx** [comment]
I've merged https://github.com/tudat-team/tudat-space/pull/148, which works exactly as it should, many thanks for this improvement. It's going to help us out a lot in ensuring consistency!

If you could do:

> Add a repository secret GH_PAT to tudatpy-examples with permissions to push to tudat-space

I can merge this as well!

**Comment by DominicDirkx** [comment]
You should have access now. Let's first get this to work, the see if we should create/revive a bot

**Comment by larshinueber** [comment]
Thank you!
The `GH_PAT` is already set (I assume that's from the previous version of the Github action), so from my side this PR is ready to be merged. If the PAT doesn't work anymore I will update it with a new one :)

**Comment by DominicDirkx** [comment]
Great! Merged :)

**Comment by DominicDirkx** [comment]
It doesn't work yet, I'm afraid:
https://github.com/tudat-team/tudatpy-examples/actions/runs/10715714863/job/29711709939
with error:
Error: fatal: could not read Username for 'https://github.com/': terminal prompts disabled
Is this something you encountered in your local test setup?

**Comment by larshinueber** [comment]
It should have worked now :)
I created a new token and added it to the repository secrets. Following [this issue](https://github.com/actions/checkout/issues/664) I set the expiry date to 05/09/2025, so the token needs to be updated next year.

Let me know if there is anything else :)

**Comment by DominicDirkx** [comment]
This works! Could you briefly describe here how/where to update this token?

**Pull request merged**
