### PR TITLE
Fix ascent example

### PR DESCRIPTION
**Pull request by larshinueber**
Hi all,

This is an attempt to fix the two stage rocket example, see #18 and #62.

With the current setup, it seems that https://github.com/tudat-team/tudatpy-examples/blob/0f77c84b2c0aebda30e0e9b7e60dd4922f6202b3/propagation/two_stage_rocket_ascent.py#L212 does not have an effect and the first stage is just continuously thrusting. I couldn't find any reference in the docs, was this method used to turn off the thrust before the refactoring?
To resolve this, I have added a check in the [`get_thrust_magnitude` method](https://github.com/larshinueber/tudatpy-examples/blob/d1684274a472b9ce4632292201e3330cc34c6895/propagation/two_stage_rocket_ascent.py#L221) that turns off the thrust if all fuel has been used. Is there a more elegant way to do this with the current thrust setup?

Despite this, the second stage does not reach orbit, see the Jupyter notebook in https://github.com/tudat-team/tudatpy-examples/pull/63/commits/c00fa7c2a569d5362874de5ff48bbc502324118b. Only be increasing the Isp of the second stage to 280s it reaches orbit. Maybe @DominicDirkx can give some insight if this might be related to changes in the thrust refactoring, or if similar behavior has been observed in other cases?

Other changes:
- Terminate second stage propagation if it crashes back on the surface (which shouldn't be the case, but improves robustness in case it does not reach orbit)
- Update integrator initialization to current API documentation

### CODE REVIEW

**Comment by larshinueber** [comment]
After looking back into this, it seems that the example is also sensitive to the integrator tolerances.
Even with the increased Isp of 290s, relative and absolute tolerances of 1e-13 lead to the vehicle not reaching orbit. Only when using tolerances of 1e-14 the vehicle reaches orbit. When using the original Isp of 273s, the vehicle doesn't reach orbit even with tighter integration tolerances.

@DominicDirkx Do you know by chance if the thrust model values and dry-/wet stage masses have been taken from a reference? Is it expected for the vehicle to reach orbit with the original values or have they been chosen (somewhat) arbitrarily?

**Comment by larshinueber** [comment]
Thank you for the clarification!

I suspect the behavior was caused by an interaction between the maximum integrator step size and the way the termination condition of the first integration is implemented. By reducing the maximum step size, the termination condition is triggered earlier and the second stage is more likely to recover the falling vehicle. I added a note on the sensitivity of the integrator choice.

The PR is now ready to merge from my side.

**Comment by DominicDirkx** [comment]
Thanks! It's great to have this example back up and running, I see that the notebook here:

https://github.com/tudat-team/tudatpy-examples/blob/c681eed3fd4fd06ed79c7301c82ecb1e9b798e4f/propagation/two_stage_rocket_ascent.ipynb

thinks it's invalid. Could you verify that it's up to date (possibly just a github rendering issue)

**Comment by larshinueber** [comment]
Thanks for catching that!
It was an issue with the file from the merge, should be fixed now and ready to merge :)

**Pull request merged**
