### PR TITLE
Automated synchronization of directories over several repositories

### PR DESCRIPTION
**Pull request by kgzenk**
Only thing left to do is to create a GitHub token and save it as a secret with the variable name GH_PAT.

### CODE REVIEW

**Comment by DominicDirkx** [comment]
Hi Kai, thanks! A couple of questions:

*Could you explain what gets synced with what here exactly? We now have the examples on tudat-space (as .ipynb) and in this repo (as .ipynb and .py). Which is used as the 'master' repo? Ideally, that would be this repo (?), and if there is any update here, the new Jupyter notebook gets copied into the tudat-space repo. 
* How does this pull request interact with the other two (Mex and Galilan moons)? Can they be merged separately?
* Go ahead and add the Github token. For which repo/organization would you need access?

**Comment by kgzenk** [comment]
As the code stands now, every time a pull request is closed successfully - i.e. it is merged with the master branch - a line of events is triggered ultimately resulting in a pull request in the tudat-space repo. Hence, this repo here (tudatpy-examples serves as kind of 'master' repo for this case if one were to say so). Unfortunately, GitHub is not smart enough to only sync all .ipynb files, but can only sync the entire folder. I have however created a comment for the reviewer of every pull reuest in the tudat-space repo asking to remove all files that are no notebooks. I know, this is not ideal and still requires some manual work, but is the best thing possible (for now)...

The other files can be merged separately, I might have created the feature-branch from a wrong (i.e. not the master) working branch.

**Comment by DominicDirkx** [comment]
The token has been added and approved, and #25 is also ready to be merged as far as I'm concerned. If all is ready, let me know, and we can merge this one first, then #25, and then see if it does its magic!

**Comment by kgzenk** [comment]
Theoretically, everything should be ready and working (fingers crossed). Indeed, that would be the preferred merging-order!

**Pull request merged**
